### ISSUE TITLE
BUG: Characters can't learn most new spells from this mod.

### ISSUE THREAD

**Issue by Endarire** [SpellholdStudios/Region_of_Terror#53]
Greetings, @Roberciiik!

I tested the latest master branch today and found what seemed to me like bugs.  I chose the newest master branch since it seemed like it would have fewer bugs than the latest release.  (If you were already amidst fixing these, that's even better!)

I was fairly certain a generalist Wizard was intended to be able to learn all the new spells from scrolls except _hero,_ but these were the only ones I was able to learn from scrolls.

-Ice Exploder

-Improved Invisibility 10' Radius

-Poison Shield

-Wake of the Inferno

As a Sor, these were the only spells I was able to learn at character creation or level time.  I also started a new Wizard in _Throne of Bhaal_and could only learn these at character creation. 
-Eagle's Splendor

-Monster Summoning IV

-Monster Summoning V

Thankee!

**Comment by Roberciiik** [comment]
Please do not tag people by the GitHub nicknames if the issue is not directly related to them. This is a public repository and everyone is welcome to contribute and work on the suggestions, issues or bugs. The fact I've contributed to this modification does not mean that I am now the owner and I should be poked on every opened issue. Thank you for understanding.

**Comment by Endarire** [comment]
I apologize.  I pinged you specifically because of our conversations on SHS and your seeming fluency with this mod.

**Comment by Roberciiik** [comment]
Either way, everyone can try to resolve the issue, so this is a wrong assumption. Thanks.
